sudo: required

language: node_js

node_js:
  - 'stable'
addons:
  chrome: stable

before_deploy:
  - npm run build

deploy:
  provider: script
  script:
    - 'echo "TODO: deploy the app. Directory listing:" && ls -R dist'
  skip_cleanup: true
  on:
    branch: master
